### ISSUE TITLE
[pyflor_install] Error when running pyflor_install

### ISSUE THREAD

**Issue by bobbyy98** [ucbrise/flor#51]
```
Traceback (most recent call last):
  File "/anaconda3/envs/ml/lib/python3.7/site-packages/conda/common/configuration.py", line 42, in <module>
    from cytoolz.dicttoolz import merge
ModuleNotFoundError: No module named 'cytoolz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/envs/ml/bin/pyflor_install", line 10, in <module>
    sys.exit(install())
  File "/anaconda3/envs/ml/lib/python3.7/site-packages/flor/__main__.py", line 65, in install
    import conda.cli.python_api
  File "/anaconda3/envs/ml/lib/python3.7/site-packages/conda/cli/python_api.py", line 9, in <module>
    from ..base.context import context
  File "/anaconda3/envs/ml/lib/python3.7/site-packages/conda/base/context.py", line 21, in <module>
    from ..common.configuration import (Configuration, LoadError, MapParameter, PrimitiveParameter,
  File "/anaconda3/envs/ml/lib/python3.7/site-packages/conda/common/configuration.py", line 47, in <module>
    from .._vendor.toolz.functoolz import excepts
  File "/anaconda3/envs/ml/lib/python3.7/site-packages/conda/_vendor/toolz/functoolz.py", line 467
    f.__name__ for f in reversed((self.first,) + self.funcs),
    ^
SyntaxError: Generator expression must be parenthesized
```

**Comment by bobbyy98** [comment]
Resolved by fixing dependencies.
