### ISSUE TITLE
[pyflor_install] Could not find environment bug 

### ISSUE THREAD

**Issue by bobbyy98** [ucbrise/flor#52]
```
The Flor installer needs to copy and transform an anaconda environment.
This installer will take some time to complete.
Continue with installation [Y/n]? Y
Enter the source anaconda environment [base]:
Enter the Python version of the source anaconda environment [3.7]:
Enter the name of the new anaconda environment [flor]:
Traceback (most recent call last):
  File "/anaconda3/envs/ml/bin/pyflor_install", line 11, in <module>
    load_entry_point('pyflor', 'console_scripts', 'pyflor_install')()
  File "/Users/bobby/Dropbox/Berkeley/RISELab/flor/flor/__main__.py", line 130, in install
    conda.cli.python_api.run_command('create', '--name', conda_flor_env, '--clone', base_conda)
  File "/anaconda3/envs/ml/lib/python3.7/site-packages/conda/cli/python_api.py", line 85, in run_command
    raise e
  File "/anaconda3/envs/ml/lib/python3.7/site-packages/conda/cli/python_api.py", line 81, in run_command
    return_code = args.func(args, p)
  File "/anaconda3/envs/ml/lib/python3.7/site-packages/conda/cli/main_create.py", line 68, in execute
    install(args, parser, 'create')
  File "/anaconda3/envs/ml/lib/python3.7/site-packages/conda/cli/install.py", line 211, in install
    clone(args.clone, prefix, json=context.json, quiet=context.quiet, index_args=index_args)
  File "/anaconda3/envs/ml/lib/python3.7/site-packages/conda/cli/install.py", line 59, in clone
    src_prefix = context.clone_src
  File "/anaconda3/envs/ml/lib/python3.7/site-packages/conda/base/context.py", line 345, in clone_src
    return locate_prefix_by_name(self, self._argparse_args.clone)
  File "/anaconda3/envs/ml/lib/python3.7/site-packages/conda/base/context.py", line 743, in locate_prefix_by_name
    raise CondaEnvironmentNotFoundError(name)
conda.exceptions.CondaEnvironmentNotFoundError: Could not find environment: base .
You can list all discoverable environments with `conda info --envs`.
```

**Comment by bobbyy98** [comment]
Fixed by using subprocess for installation and uninstallation.
